# Generated by Django 5.0.4 on 2024-05-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteDetails',
            fields=[
                ('vessel_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('current_port', models.CharField(max_length=100)),
                ('current_port_latitude', models.FloatField()),
                ('current_port_longitude', models.FloatField()),
                ('destination_port', models.CharField(max_length=100)),
                ('destination_port_latitude', models.FloatField()),
                ('destination_port_longitude', models.FloatField()),
            ],
        ),
    ]
